### ISSUE TITLE
iOS 13.6.1 Instagram share option does not work

### ISSUE THREAD

**Issue by robertovanderlinden** [vstirbu/InstagramPlugin#115]
We use this plugin ([Pull request](https://github.com/vstirbu/InstagramPlugin/issues/111) version)  with ionic 5 and iOS 13.6.1. When sharing content, iOS shows two options:

- Instagram (Does not work, see attachment)
- Copy to Instagram (works as expected)

![image (1)](https://user-images.githubusercontent.com/10807693/91575274-a5b0d200-e947-11ea-99c9-399c16383e47.png)

Is anyone else experiencing this or has an idea to fix this?

**Comment by rodrigograca31** [comment]
You are saying that PR works but one of the options doesn't work?

Im asking because I was looking for feedback to know if it worked or not to be able to merge it:
https://github.com/vstirbu/InstagramPlugin/pull/114#issuecomment-633210264

**Comment by robertovanderlinden** [comment]
Yes we are using the pull request and it works, but now something changed in either iOS or Instagram and that results in this issue.

**Comment by rodrigograca31** [comment]
Ok, I merged it.

Sorry but I'm not an iOS developer.

This seems to be the changelog:

```
iOS 13.6.1 includes bug fixes for your iPhone.

Addresses an issue where unneeded system data files might not be automatically deleted when available storage is low
Fixes a thermal management issue that caused some displays to exhibit a green tint
Fixes an issue where Exposure Notifications could be disabled for some users
```

**Comment by hdeshmukh** [comment]
Still experiencing this issue. Updated to 0.6.0 that incorporates the PR #114 mentioned but still seeing the issue occur. Download the file from a url into base64 image and using the share method, but this all of a sudden stopped working.

**Comment by rodrigograca31** [comment]
@regevbr pinging you because I noticed that you know Objective C and Cordova "things" and you might be able to help to fix this.

Also because @drastik mentioned before on #114 that he would be up to paying someone to fix it.

**Comment by regevbr** [comment]
Thanks but I actually have no expirience with iOS and I hate apple as well haha don't know anyone who can help sadly

**Comment by rodrigograca31** [comment]
Oh ok!  I saw your iOS code on the other plugin and thought......... Thanks anyways!

**Comment by regevbr** [comment]
It was a simple 3 liner that worked out of the box bu chance 😂
